name 'rubies'
maintainer 'Jason Blalock'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures rubies'
long_description 'Installs/Configures rubies'
version '0.1.0'

depends 'apt' , '~> 3.0.0'
depends 'chruby_install', '~> 0.1.3'
depends 'ruby_install', '~> 1.0.5'
